chat/urls.py
from django.urls import path
from . import views
# from .views import CustomLoginView

app_name='chat'

urlpatterns = [
    path('', views.chatView, name='chat'), 
]

dashboard/urls.py
from unicodedata import name
from django.urls import include,path
from . import views
# from .views import CustomLoginView

urlpatterns = [
    # path('login/', CustomLoginView.as_view(), name='login'),
    path('', views.dashboardView, name='dashboard'),
    path('project_view/<int:project_id>/', views.projectView, name='project_view'),
    # path('chat/', include('chat.urls', namespace='chat')),
]

visn2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('frontpage.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('contacts/', include('contacts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('files/', include('files.urls')),
    path('projects/', include('projects.urls')),
    
]

dashboard/models.py
from django.db import models

# Create your models here.
# after modifying models.py must migrate changes to database:
# ./manage.py makemigrations
# ./manage.py migrate
from datetime import datetime
from email.policy import default
from operator import mod
from pyexpat import model
from random import choices
from django.db import models
from django.conf import settings
# from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

# Create your models here.

# models: https://docs.djangoproject.com/en/3.2/topics/db/models/


class Message(models.Model):
    id = models.AutoField(primary_key=True)
    mfrom = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mfrom')
    mto = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mto')
    msg = models.TextField()
    msgTime = models.DateTimeField(default=datetime.now)

class Project(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, null=False)
    deadline = models.DateTimeField()
    discription = models.TextField()
    tasks = models.TextField()
    create_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="author of project", related_name='create_user')
    members = models.ManyToManyField(User, verbose_name="members of project", related_name='pmembers')

    def __str__(self):
        return self.name

class ProjFile(models.Model):
    id = models.AutoField(primary_key=True)
    project = models.ForeignKey('Project', on_delete=models.CASCADE, related_name='project')
    filename = models.FileField(upload_to='')
    comment = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')


class Task(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    status = models.BooleanField(default=False)
    project = models.ForeignKey('Project', on_delete=models.CASCADE, related_name='tproject')

# class Upload(models.Model):
#     description = models.CharField(max_length=100)
#     comments = models.TextField(blank=True)
#     filename = models.FileField(upload_to='')

#     def __str__(self):
#         return self.description


# class UserProject(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='puser')
#     project = models.ForeignKey('Project', on_delete=models.CASCADE, related_name='pproject')


# class MyUser(models.Model):
#     name = models.CharField(max_length=20, unique=True)
#     password = models.CharField(max_length=512)
#     userType = models.IntegerField(default=1) #1 client 2: programer

# class Messages(models.Model):
#     mfrom = models.ForeignKey(User, on_delete=models.CASCADE, related_name='msfrom')
#     msg = models.TextField()
#     mto = models.ForeignKey(User, on_delete=models.CASCADE, related_name='msto')

# class Messages(models.Model):
#     mfrom = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='mfrom')
#     msg = models.TextField()
#     mto = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='mto')



# class DjUser(AbstractUser):
#     userType = models.IntegerField(choices=((1, 'client'), (2, 'Freelancer')))



# class Message(models.Model):
#     mfrom = models.ForeignKey('DjUser', on_delete=models.CASCADE, related_name='mfrom')
#     msg = models.TextField()
#     mto = models.ForeignKey('DjUser', on_delete=models.CASCADE, related_name='mto')
#     msgTime = models.DateTimeField(default=datetime.now)

# class Message(models.Model):
#     mfrom = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='mfrom')
#     msg = models.TextField()
#     mto = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='mto')
#     msgTime = models.DateTimeField(default=datetime.now)

# class Project(models.Model):
#     freelancer = models.ForeignKey('DjUser', on_delete=models.CASCADE, related_name='freelancer')
#     client = models.ForeignKey('DjUser', on_delete=models.CASCADE, related_name='client')
#     name = models.CharField(max_length=100, null=False)
#     deadline = models.DateTimeField()
#     discription = models.TextField()

#     def __str__(self):
#         return self.name



##### Mingyuans models above ^^^^^
##### Daniels models below vvvvvvv

# class Project(models.Model):
#     name = models.CharField(max_length=100, null=False)
#     deadline = models.DateTimeField()
#     discription = models.TextField()

#     def __str__(self):
#         return self.name


# class Message(models.Model):
#     sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sender')
#     reciever = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='reciever')
#     msg = models.CharField(max_length=100)
#     msgTime = models.DateTimeField(default=datetime.now)

dashboard/forms.py
# docs forms: https://docs.djangoproject.com/en/3.2/topics/forms/ 

from pyexpat import model
from statistics import mode
from xml.dom import ValidationErr
# from attr import attrs
from django import forms
from django.forms import widgets
# from django.contrib.auth.forms import UserCreationForm
from .models import *

# ModelForm: https://docs.djangoproject.com/en/3.2/topics/forms/modelforms/

class ProjFileForm(forms.ModelForm):
    class Meta:
        model = ProjFile
        exclude = ['author', 'id']
    

class NewProjForm(forms.ModelForm):
    class Meta:
        model = Project
        exclude = ['create_user', ]
        
class MessageForm(forms.Form):
    mto = forms.CharField(min_length=5, label='to name', required=True, widget=forms.HiddenInput())
    message = forms.CharField(widget=widgets.Textarea(attrs={'rows': 1}), label='message text', required=True)

class NewTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ['id', 'status']
    # project = forms.ModelChoiceField(queryset=None)
    # form.fields['books'].queryset 


# class UploadForm(forms.ModelForm):
#     class Meta: 
#         model = Upload
#         fields = ('description', 'comments', 'filename')


# class MyUserForm(forms.Form):
#     name = forms.CharField(min_length=5, label='name', required=True)
#     password = forms.CharField(min_length=4, label='password', required=True)
#     password2 = forms.CharField(min_length=4, label='confirm password', required=True)
#     userType = forms.ChoiceField(choices=[(1,'client'), (2, 'programer')], label='user type')

#     def clean(self):
#         ps = self.cleaned_data.get('password')
#         ps2 = self.cleaned_data.get('password2')
#         if ps == ps2:
#             return self.cleaned_data
#         self.add_error('password2', ValidationErr('confirm password error!'))

# class LoginForm(forms.Form):
#     name = forms.CharField(min_length=5, label='name', required=True)
#     password = forms.CharField(min_length=4, label='password', required=True)

# class MyUserCreationForm(UserCreationForm):
#     userType = forms.ChoiceField(choices=[(1,'client'), (2, 'Freelancer')], label='user type', required=True)
    
#     class Meta(UserCreationForm.Meta):
#         model = DjUser
#         fields = ['username', 'password1', 'password2', 'userType']


dashboard/views.py
import math
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.urls import reverse_lazy
from django.forms import model_to_dict
from .models import *
from .forms import *
from django.db.models import Q



def dashboardView(request):
    context = {}
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('login'))
    projects = Project.objects.filter(Q(create_user=request.user) | Q(members=request.user)).all()[:]
    res = []
    for i in range(math.ceil(len(projects)/3)):
        res.append(projects[i * 3: (i+1)*3])
    context['projects'] = res
    print(projects)
    users = User.objects.all()
    chat_form = MessageForm()
    context['target_users'] = users
    context['chat_form'] = chat_form
    if request.method == 'POST':
        f = MessageForm(request.POST)
        print('aaa')
        if f.is_valid():
            print('save')
            to_name = f.cleaned_data.get('mto')
            mto = User.objects.filter(username=to_name).first()
            Message(mfrom=request.user, msg=f.cleaned_data.get('message'), mto=mto).save()
    return render(request, 'dashboard/dashboard.html', context)

def projectView(request, project_id):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('login'))
    project = Project.objects.filter(id=project_id).first()
    if project:
        res = model_to_dict(project, fields=['id', 'name', 'deadline', 'discription', 'tasks'])
        file_query = ProjFile.objects.filter(project=project)
        file_number = file_query.count()
        file_infos = [str(f.filename) for f in file_query]
        tasks = Task.objects.filter(project=project).all()
        res['task_texts'] = [t.name for t in tasks]
        if len(tasks):
            res['ratio'] = round(len([t.name for t in tasks if t.status]) / len(tasks) * 100)
        else:
            res['ratio'] = 0
        res['file_number'] = file_number
        res['file_infos'] = file_infos
        res['create_user'] = project.create_user.username
        return JsonResponse(res)

dashboard/templates/dashboard/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">

    <link href="{% static 'css/base.css' %}" rel="stylesheet"/>
    
    {% block styles %}
    <!-- block of style links for each page -->
    {% endblock styles%}
    

</head>
<body>
    <!-- Navbar -->
    {% include 'dashboard/navbar.html' %}

    <!-- inhertiting from base -->
    {% block content %}
    {% endblock content %} 

    {% include 'dashboard/message-icon.html' %}
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="{% static 'js/zepto.min.js'%}" ></script>
<script src="{% static 'js/proj.js'%}" ></script>
<script src="{% static 'js/chat.js'%}" ></script>
</body>
</html>

dashboard/templates/dashboard/dashboard2.html
<h3>Hello, {{request.user}}</h3>
<br>
<br>
<a href="{% url 'logout' %}">Logout</a>

dashboard/templates/dashboard/message-icon.html
{% load crispy_forms_tags %}

<!-- Message Icon -->
   <div class="container fixed-bottom text-end me-5 pb-5">
<button id="chat_ui" style="background-color: white; border:none;">
        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-chat-right-text" viewBox="0 0 16 16">
            <path d="M2 1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h9.586a2 2 0 0 1 1.414.586l2 2V2a1 1 0 0 0-1-1H2zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z"/>
            <path d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
        </svg>
    </div>
</button>

<div id="chatback" style="display: none;position: absolute;top: 0%; left:0%; width:100%; height:1100px; background-color:black; z-index:1;-moz-opacity: 0.5; opacity:0.5;"></div>

<li id="chat_li" style="display: none; position: absolute;top:25%;left:25%;border:3px solid #ccc;background:white;z-index: 2;width: 600px; height: 260px; padding: 20px;">
    <label id="x" style="position: relative;top:0px;left: 95%;font-size: 25px;cursor: pointer;">x</label>
    <div>
       {% for target_user in target_users%}
       <button class="talker_button" talker="{{target_user.username}}" >{{target_user.username}}</button>
       {%endfor%}
    </div>
    <form method="POST">

       <!-- Cross Site Request Forgery: https://docs.djangoproject.com/en/3.2/ref/csrf/ -->
       {% csrf_token %}
 
       {{ chat_form|crispy }}
    
       <button type="submit" class="btn btn-success btn-lg">send</button>
 
    </form>
</li>

dashboard/templates/dashboard/navbar.html
{% load static %}

<nav class="sticky-top navbar navbar-expand-md navbar-dark bg-dark pb-1 pt-1" aria-label="Fourth navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><img src="{% static 'images/visn-logo.png' %}" class="rounded-1 border border-danger" width="100" height="30"></a>
        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarsExample04">
            <ul class="navbar-nav me-auto mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'dashboard' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contacts' %}">Contacts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'files' %}">Files</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'projects' %}">Projects</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'chat:chat' %}">Chat</a>
                </li>
                
            </ul>
            <div class="navbar-nav">
                <div class="nav-item mt-2 me-2 pt-1">
                    <a class="nav-link">Hello, <span style="color:rgb(250, 212, 107);">{{request.user.username}}</span></a>
                </div>
                
                <!-- <img src="#" width="30" height="30" class="invisible"> -->
                <!-- nav togler -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <!-- user icon -->
                                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="gray" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end mt-2" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- <i class="bi bi-gear" width="30" height="30"></i> -->
                <div class="nav-link">
                    <!-- <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="white" class="bi bi-gear" viewBox="0 0 16 16">
                        <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"></path>
                        <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z"></path>
                    </svg> -->
                    <!-- nav togler -->
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <!-- user icon -->
                                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="white" class="bi bi-gear" viewBox="0 0 16 16">
                                        <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"></path>
                                        <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z"></path>
                                    </svg>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end mt-2" aria-labelledby="navbarDarkDropdownMenuLink">
                                    <li><a class="dropdown-item" href="{% url 'pass_change' %}">Change Password</a></li>
                                    <li><a class="dropdown-item" href="{% url 'email_change' %}">Change Email</a></li>
                                    <li><a class="dropdown-item" href="#">Change Phone Number</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>                    
                </div>
                
            </div>
        </div>
    </div>
</nav>